### ISSUE TITLE
MSB small mistake

### ISSUE THREAD

**Issue by andrew-aladev** [merrilymeredith/rb-compress-lzw#1]
Hello. You made a small mistake that makes msb mode invalid.

```
self[pos + (@msb_first ? (width - bit_offset ) : bit_offset)] =
```

For example `bit_offset` is between [0, 7], `width - bit_offset` is between [1, 8]. `width - bit_offset - 1` is a right solution.

**Comment by andrew-aladev** [comment]
PS as I know MSB applies only to compressed content itself. 3 first bytes should not be written with reversed bits.

**Comment by mariduv** [comment]
Good catch, and thank you!   I haven't really looked back at this since I churned it out for practice years ago, but this also gave me the opportunity to clean up some new warnings from a more recent ruby.
